apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: workshop-app
  name: app-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: ocs-external-storagecluster-cephfs
