apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- solutions-github.secret.yaml
- workshop.namespace.yaml
- workshop.buildconfig.yaml
- workshop.imagestream.yaml
- image-puller.rolebinding.yaml
