kind: Secret
apiVersion: v1
metadata:
  name: workshop-app-github
  namespace: workshop-app
data:
  password: ENC[AES256_GCM,data:t7UzdbNxOPTvtOao+103lEy4B9/N+mvmW1SUsqZR+8l+L7kOPRFqWig6qSWOGMnEpOWmy6go2f6SuOz4dsmZrSLKL/wZZ8yzdLWpKbT0vYItsXztOeFxNDY0IDm+iWy5L4MfA2czOcL8hsd0J1YePC+O+udttFJS9+Hojg==,iv:E9NDH+HtgXrQ/OqBupPrO7B1TBk6qAGsTBvN17p6r6c=,tag:nAeWzrAqZjcx2ngywIyUEQ==,type:str]
  username: ENC[AES256_GCM,data:AW0s7A==,iv:d6DB+k5knIya6THUlbci+X79QZ/i9uTy67uzfWjddeQ=,tag:N0C1Aa7UYzAmLPfLdp5n2A==,type:str]
type: Opaque
sops:
  lastmodified: "2025-09-24T14:19:54Z"
  mac: ENC[AES256_GCM,data:hILN7ngagQ71JP4VhqR4BoHSQyO3MS6httI203lDBfF0frwHMD+Q5i4FFV5qfPkI/i4wSCEYH2/LtLT9Qdmj0p+itO/Hw5UfCAjAQPa8usvasnIqLMI15KPPzpKdocWQTn7PUgkWiYOOKy4etVvFGGogLzs7dhSl8TjzNyc14F8=,iv:4Fazu2bbG62e6w3qO7S5z2c+w708MZHNqLr+67xIApo=,tag:1FH/FBqh97EHMccD0QYSaQ==,type:str]
  pgp:
  - created_at: "2025-09-24T14:19:54Z"
    enc: |-
      -----BEGIN PGP MESSAGE-----

      hQIMA4w5Pq+4Nf1+ARAAk7c7G7enoNNemNrtlywDtvQteXVzP4ThWLIpE6/ms0HL
      rzFAC/nCskhrKNiRwPtMalGQD5/ZomYMbzzYSsmh+isxXlwRH9/bJyVOk60ObAz3
      SO2quXQTBWBrSD/fcYjRkp1BzP4NalDU5nOIvY3JovRO4H6f9EKhqdWn0g889B/s
      f74RVc4a4woZA2CI6hSRMrXmdPT1PrKYwQsuFXw0a7gj+ye+9NuNi1cDu70X4DA/
      iusLiPnbtmbbko+/WBCwiuEa8o3sONcaovENWToBVAHHtzNYsojSoBdOeN5TG22m
      PfrFOeFkp4Ha7tpy9tZZgilm/bBrT1A3dJfC5GsMPRGTnK/VKIJ5zg5yiHHKi+4M
      RQp2COgWaQSyBwAq7zut84dNLF6nZRrCK7F2uoKCjgOXqyV9+KI/tPa3QgGuOlu+
      c0LYtxjYCPWHW4pz8mPw73d51H/ht7VD2g8YbW++xle6QxD45ZDH6aoeEyGy+A3F
      vf4bVsttK5kQn4LWn2LIwnrf+79IOtuzOvBwJmZJ/MOMq0Lz28ST6j6e1O8SY2Y2
      rjerJgznTneqH/Vc2V4ryaBbLIb11bELtt8+mX5QCMhlk4j8zW2HvJdllCC8r1ww
      AnPL5+qBIYOk6qkQcF+QkNEeYezrZVUMHGlGK69c9xILHdG6p4Qk+0WBRfcSJJbU
      aAEJAhDpUOe9CLdcRzXxCgD9TcPA4B0mg6+SylupDl7/8jtVgsJtL6qvcv5CO3PS
      1lH/sKJv2WAS2NyEH2dUpbxQR/q5XjxXUZ1l10ZEtYMy8nIsn0ejEMIXrKHGmqJW
      joZvvwSGtR40
      =JObg
      -----END PGP MESSAGE-----
    fp: EF47395218432BD3DECACDC714337829F8444AA6
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
