apiVersion: v1
stringData:
  password: ENC[AES256_GCM,data:IwzHyPC+f/55t451uKZt2ENlrwie0w//yHJBNkR/ihwGJSrLH1KrMpDwR93dwd50mj+sNyMlIrexgSZH27/b8fgWmlkiqrhV3G+7xA9ddA5sbSXvghCZojit9mwn,iv:ohRqazcEEGGPto1hB45ZSJDKiDLTKh8rPahGFOa4wwE=,tag:9+pNLpuXoNQQgNxm5MKPHw==,type:str]
  username: ENC[AES256_GCM,data:4QaW,iv:Y9nMVBl8cz64dxWOjwDdQeB3eD3FOGhVM7Ox+vGwvE0=,tag:N9c1YRLIRmQfJf7vreHUDw==,type:str]
kind: Secret
metadata:
  name: workshop-app-github
  namespace: workshop-app
type: Opaque
sops:
  lastmodified: "2026-02-09T14:47:48Z"
  mac: ENC[AES256_GCM,data:liT/MgN7sG+optTMrcpDCSy6yqrEspI3LbqIeARJU0k+3qzXeXOXob131Lh8NlvDQDkRyTrU91iNHtKqyJW5k8bO5/GAdq7LujtorOJKHLqdD9TAVj7smNPDl55ChukGM3tXVo2CRTIJFooXe61k8uocYtzOR3iu0lXnP61T6AY=,iv:BscHs0fLIWZsMO6XDU2/bxcBomcb8bUsh8sutsTx1cU=,tag:C0/U7dOYR7Fr8ArVBGA1eQ==,type:str]
  pgp:
  - created_at: "2026-02-09T14:47:48Z"
    enc: |-
      -----BEGIN PGP MESSAGE-----

      hQIMA4w5Pq+4Nf1+AQ//Xq83mbd+JmK3bchkLUlgKIr26CnaLAAibUSaZ8hR5qt1
      +VP4L0NThxllNR47ltBPc33bqYYiMHBlhl7uoa7MbiEQxA9GIwsW6eS/ZTngOJz5
      mSJYI1ND0VBuInOgV0OulRB7xnPXNoIRBTmQOFe1OalOgmMI+zA0uj+Gx1jun7QT
      nCZoUv+yVtwn/vKQmFtg8VI/Eb7fDnXoy4JJQjFe96qxjs0UJH8l9kNqzkM5cEoY
      nYh13XnA4zB/afLUVfGEski1mkyoT0ksLOZuEErvUylSpQ/rmeAdEb4erLdFX2nB
      5bR9Lhqzc/Lm3TuwW1sK3FabVmt09l3rwdunSB0uy08wkDG2WumBYIr22t5eMBEA
      wZ1rKVmKF/QKUgFnZUoQlpFkLY8AW5yPNhCwtC+QfMPUkneiONGZUXFe2gceUaXA
      BgCbI6vscXptzWs3LEC4TzjaJ+pFNCNAHCSHOi4PKeuQghOgv5OGZLeT+YiaxFU+
      Th/LQSNKpC3dqH5ZyHdHeDQeTK35KmnTyRc/gvvZnZZVdLlkCQ6O5qRLgi1sSAKm
      qhh4yIp/FROdS5WXclBMyN6YukoER6dzhjj7hEuW38GBfKWaiq7But9nFMwqW5+8
      oDixzPrbvdufGkRq0WBS98d5q0dGeJnT6g6bnOk5HxZFxLAX3xcniT/gWJJL+1XU
      aAEJAhC8gTKc6XRDKd7OGw6LI8t0LrWUzNlyxscarj93Zuy6BS3m0J9YWTjYWUfn
      8JJz8BHHUq0GgkC3sRUYsXrrbtm6JYK6HgTjb/XoPBSfUd+tU1IV8p9/OUkK44TW
      7yJ6jzkAR7yA
      =49+Q
      -----END PGP MESSAGE-----
    fp: EF47395218432BD3DECACDC714337829F8444AA6
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
