kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: build-workshop-app
  namespace: workshop-app
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'workshop-app:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/ConSol-AndreasHahn/openshift-workshop-resources.git'
      ref: 'refs/heads/main'
    contextDir: "workshop-app-ts"
    sourceSecret:
      name: workshop-app-github
  runPolicy: Serial
  triggers:
  - type: ConfigChange
