apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: workshop-app
  template:
    metadata:
      labels:
        app: workshop-app
    spec:
      serviceAccountName: image-puller
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: workshop-app
            topologyKey: kubernetes.io/hostname
      containers:
      - name: workshop-app
        image: image-registry.openshift-image-registry.svc:5000/workshop-app/workshop-app:latest
        env:
        - name: GREETING_DEFAULT
          value: "Max Mustermann"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 256Mi
