apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    image:
      registry: docker.io
      repository: bitnamilegacy/nginx
      tag: 1.29.1
    staticSiteConfigmap: static-site
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 100m
        memory: 512Mi
    ingress:
      enabled: true
      hostname: nginx-solution-13.apps.cluster-dhljm.dynamic.redhatworkshops.io
      tls: true
      selfSigned: true

