kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-special
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          allowme: please